apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-from-git-task
spec:
  # params:
  resources:
    inputs:
      - name: workspace
        type: git
        targetPath: simple-with-inputs-and-params/tekton-spring-sample
  steps:
    - name: build-sources
      image: maven:3.6.3-openjdk-15-sli
      command:
        - mvn
      args: ['clean', 'install']